---
name: DEFAULT
description: Default vulnerability workflow.
priority: 1
conditions: []
states:
  - name: NEW
    description: >
      A new ticket arrived from incoming queue without any validation
      or analysis performed yet.
    jira_state: New
    jira_resolution: null
    requirements: []

  - name: TRIAGE
    description: >
      Queue captain has taken a ticket off the incoming queue and will
      evalute if it should be rejected or qualified for further steps in
      the workflow.
    jira_state: Refinement
    jira_resolution: null
    requirements:
      - has owner

  - name: PRE_SECONDARY_ASSESSMENT
    description: >
      Task qualified for further work and has initial data filled, triage
      trackers have been filled.
    jira_state: To Do
    jira_resolution: null
    requirements:
      - has affects
      - has impact
      - has source
      - has title
      - has trackers

  - name: SECONDARY_ASSESSMENT
    description: An analyst assigned the task to themselves.
    jira_state: In Progress
    jira_resolution: null
    requirements:
      - has owner

  - name: DONE
    description: >
      Task is done. We commonly expect that a CVE will be 
      published, but it is not a requirement.
    jira_state: Closed
    jira_resolution: Done
    requirements: []
