name: Meta checks
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check existence of CHANGELOG entry
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: docs/CHANGELOG.md
          noChangelogLabel: technical
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
