name: Test
on:
  workflow_run:
    workflows: [Lint]
    types: [completed]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: quay.io/prodsecdev/fedora-latest:35
      credentials:
        username: ${{ secrets.QUAY_REGISTRY_USERNAME }}
        password: ${{ secrets.QUAY_REGISTRY_TOKEN }}
    # this is required in order to have the job run only if the dependent
    # workflow succeeded, see GitHub docs for more info
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    services:
      postgres:
        image: registry.redhat.io/rhel8/postgresql-13:1
        env:
          POSTGRESQL_ADMIN_PASSWORD: test
          POSTGRES_DATABASE: osidb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_HOST: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        credentials:
          username: ${{ secrets.RH_REGISTRY_USERNAME }}
          password: ${{ secrets.RH_REGISTRY_TOKEN }}
      testldap:
        image: quay.io/prodsecdev/openldap:2.5.7-debian-10-r57
        env:
          LDAP_ROOT: dc=redhat,dc=com
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: adminpassword
        credentials:
          username: ${{ secrets.QUAY_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: dnf install -y openldap-devel openldap-clients python3.9
      - name: Setup LDAP service
        run: ldapadd -c -H "ldap://testldap:1389" -x -D "cn=admin,dc=redhat,dc=com" -w "adminpassword" -f etc/openldap/local-export.ldif || true
      - name: Run OSIDB tests
        env:
          ET_URL: ${{ secrets.ET_URL }}
          PRODUCT_DEF_URL: ${{ secrets.PRODUCT_DEF_URL }}
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
        run: tox -e ci-osidb
